name: Daily Scraper and Upload

on:
  push:
  schedule:
    - cron: '30 6 * * *'
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      # =========================
      # FTP SERVER 1
      # =========================
      - name: Upload to FTP Server 1
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/data/
          exclude: |
            **/*
            !attendance.json

      # =========================
      # FTP SERVER 2
      # =========================
      - name: Upload to FTP Server 2
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_2 }}
          username: ${{ secrets.FTP_USERNAME_2 }}
          password: ${{ secrets.FTP_PASSWORD_2 }}
          server-dir: /htdocs/data/
          exclude: |
            **/*
            !attendance.json
